site_name: Progenetix Documentation
site_description: 'Read the Docs Documentation for the Progenetix oncogenomics resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022, Michael Baudis and progenetix.org'
repo_name: 'progenetix-web'

extra_css: [css/extra.css]

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - mdx_gh_links:
      user: progenetix
      repo: progenetix.github.io

theme:
  name: readthedocs
  favicon: img/site-logo-topright.png
  icon:
    repo: fontawesome/brands/github-alt 

repo_url: https://github.com/progenetix/progenetix-web

edit_uri: edit/master/docs/

nav:
  - Use Case Examples: use-cases.md
  - Services: services.md
  - Classifications and Ontologies: classifications-and-ontologies.md
  - Publication Collection: publication-collection.md
  - Changelog: changelog.md
  - BeaconPlus: beaconplus.md
  - Progenetix Site: http://progenetix.org
  - Baudisgroup: http://info.baudisgroup.org

extra:
  logo: img/site-logo-main.png
  
plugins:
  - search