site_name: Progenetix Documentation
site_description: 'Read the Docs Documentation for the Progenetix oncogenomics resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022, Michael Baudis and progenetix.org'
repo_name: 'pgx'

extra_css: [css/extra.css]

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
  - mdx_gh_links:
      user: progenetix
      repo: progenetix.github.io

theme:
  # name: readthedocs
  name: material
  palette:
    primary: deep orange
  favicon: img/site-logo-topright.png
  logo: img/progenetix_black_300.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
      

repo_url: https://github.com/progenetix/progenetix-web

edit_uri: edit/main/docs/

nav:
  - Documentation Home: index.md
  - Use Case Examples: use-cases.md
  - Services: services.md
  - Classifications and Ontologies: classifications-and-ontologies.md
  - Publication Collection: publication-collection.md
  - Changelog: changelog.md
  - BeaconPlus: beaconplus.md
  - Progenetix Site: http://progenetix.org
  - Baudisgroup: http://info.baudisgroup.org

plugins:
  - search
