site_name: Progenetix Documentation
site_description: 'Documentation for the Progenetix oncogenomics resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022, Michael Baudis and progenetix.org'
repo_name: 'progenetix-web'
extra_css: [css/extra.css]

repo_url: https://github.com/progenetix/progenetix-web
edit_uri: edit/main/docs/

###############################################################################

nav:
  - Documentation Home: index.md
  - Use Case Examples: use-cases.md
  - Services: services.md
  - Classifications and Ontologies: classifications-and-ontologies.md
  - Publication Collection: publication-collection.md
  - Changelog: changelog.md
  - Beacon<sup>+</sup> &amp; `bycon`: beaconplus.md
  - Progenetix Site: http://progenetix.org
  - Baudisgroup: http://info.baudisgroup.org

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_gh_links:
      user: progenetix
      repo: progenetix.github.io

theme:
  # name: readthedocs
  name: material
  palette:
    primary: deep orange
  favicon: img/site-logo-topright.png
  logo: img/site-logo-topright.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
      
plugins:
  - search
  - pdf-export:
      combined: true
      
# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
