filters:
  NCIT:
    label: NCIT Cancer Core
  icdom:
    label: ICD-O Histology
  icdot:
    label: ICD-O Topography
datasetIds:
  progenetix:
    label: progenetix
  arraymap:
    label: arraymap
  dipg:
    label: dipg
