filters:
  NCIT:
    label: NCIT Cancer Core
  icdom:
    label: ICD-O Histology
  icdot:
    label: ICD-O Topography
  UBERON:
    label: UBERON Anatomy Ontology
datasetIds:
  progenetix:
    label: Progenetix
  arraymap:
    label: arrayMap
