filters:
  NCIT:
    label: NCIT
  icdom:
    label: ICD-O Histo
  icdot:
    label: ICD-O Topo
datasetIds:
  progenetix:
    label: progenetix
  arraymap:
    label: arraymap
  dipg:
    label: dipg
