---
- label: "CNV Query"
  note: "Query usein 2 `start` and 2 `end` values to find (structural) variants with some fuzziness for their start and end."
  description: |
    Typically CNV Queries are performed as **Beacon Bracket Queries**. These allow
    the specification of sequence _ranges_ for both `start` and `end` positions of a
    genomic variation since one usually wants to query for _similar_ structural
    variants affecting a genomic region but potentially differing in their exact
    size.
    See also the [Beacon documentation](https://docs.genomebeacons.org/variant-queries/#beacon-bracket-queries) for more information.
  img: https://docs.genomebeacons.org/img/BeaconBracketQuery-limited-match-graphics.png
  parameters:
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      placeholder: "refseq:NC_000009.12"
    start:
      placeholder: "21000001-21975098"
    end:
      placeholder: "21967753-23000000"
    variantType:
      placeholder: "EFO:0030067 (DEL)"
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    freeFilters:
      placeholder: [NCIT:C3058]
    limit:
      isHidden: true
    skip:
      isHidden: true
- label: "Range Query"
  note: "Query for variants with overlap to a genomic range"
  description: |
    **Beacon Range Queries** are supposed to return matches of any variant with
    at least partial overlap of the _sequence range_ specified by `reference_name`,
    `start` and `end` parameters. Additionally results might be restricted to
    variants matching a given size range, variant type or base composition. 
    See also the [Beacon documentation](https://docs.genomebeacons.org/variant-queries/#beacon-range-queries) for more information.
  parameters:
    datasetIds:
      placeholder: ["examplez"]
    referenceName:
      isHidden: false
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    aminoacidChange:
      isHidden: true
    start:
      isHidden: false
    end:
      isHidden: false
    variantType:
      isHidden: false
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: false
    limit:
      isHidden: true
    skip:
      isHidden: true
  img: https://docs.genomebeacons.org/img/BeaconRangeQuery-graphics.png

- label: "Sequence Query"
  note: 'This represents the inputs for a "classic" Beacon SNV query'
  description: |
    **Sequence Queries** explore the existence of a specified sequence at a given
    genomic position. Such queries correspond to the original Beacon queries
    ("Allele Requests") and are used to match short, precisely defined genomic
    variants such as SNVs and INDELs.
    See also the [Beacon documentation](https://docs.genomebeacons.org/variant-queries/#beacon-sequence-queries) for more information.
  parameters:
    datasetIds:
      placeholder: ["examplez"]
    referenceName:
      isHidden: false
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    aminoacidChange:
      isHidden: true
    start:
      isHidden: false
    end:
      isHidden: true
    variantType:
      defaultValue: "SO:0001059"
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: false
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true
  img: false
- label: "Aminoacid Variant"
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    aminoacidChange:
      isHidden: false
    geneId:
      isHidden: false
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    variantType:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true

- label: "Genomic HGVS"
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: false
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    variantType:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true


- label: "All Fields"
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    aminoacidChange:
      isHidden: false
    geneId:
      isHidden: false
    genomicAlleleShortForm:
      isHidden: false
    referenceName:
      isHidden: false
    start:
      isHidden: false
    end:
      isHidden: false
    variantMinLength:
      isHidden: false
    variantMaxLength:
      isHidden: false
    variantType:
      isHidden: false
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: false
    bioontology:
      isHidden: false
    clinicalClasses:
      isHidden: false
    accessid:
      isHidden: false
    filterLogic:
      isHidden: false
    includeDescendantTerms:
      isHidden: false
    geoCity:
      isHidden: false
    geodistanceKm:
      isHidden: false
    sex:
      isHidden: false
    materialtype:
      isHidden: false
    referenceid:
      isHidden: false
    cohorts:
      isHidden: false
    limit:
      isHidden: true
    skip:
      isHidden: true


