---
note: ""
label: ""
description: ""
parameters:
  datasetIds:
    defaultValue: ["examplez"]
  cohorts:
    defaultValue: [""]
  assemblyId:
    placeholder: "GRCh38"
  referenceName:
    placeholder: "9"
  start:
    placeholder: "19000001-21975098"
  end:
    placeholder: "21967753-24000000"
  variantType:
    placeholder: "EFO:0030067"
  alternateBases:
    placeholder: "A"
  referenceBases:
    placeholder: "N"
  freeFilters:
    placeholder: ""
  accessid:
    isHidden: true
