---
- label: "CNV Example"
  note: "Example for focal CDKN2A deletion matches."
  description: |
    This example shows the query for CNV deletion variants overlapping the
    CDKN2A gene's coding region with at least a single base, but limited
    to "focal" hits (here i.e. <= ~2Mbp in size). The query is against the
    examplez collection and can be modified e.g. through changing the position
    parameters or data source.
  img: https://docs.genomebeacons.org/img/BeaconBracketQuery-limited-match-graphics.png
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      defaultValue: "9" #"refseq:NC_000009.12"
    start:
      defaultValue: "21000001-21975098"
    end:
      defaultValue: "21967753-23000000"
    variantType:
      defaultValue: "EFO:0030067"
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    freeFilters:
      defaultValue: [NCIT:C3058]
    limit:
      isHidden: true
    skip:
      isHidden: true

- label: "SNV Example"
  note: "Example for specific EIF4A1 mutation"
  description: |
    This example shows a core Beacon query, against a specific
    mutation in the EIF4A1 gene, in the DIPG childhood brain tumor dataset.
  parameters:
    datasetIds:
      defaultValue: ["examplez", "progenetix"]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      defaultValue: "17" #"refseq:NC_000017.11"
    start:
      defaultValue: 7577121
    end:
      isHidden: true
    variantType:
      defaultValue: "SO:0001059"
    alternateBases:
      defaultValue: "A"
    referenceBases:
      defaultValue: "G"
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true

- label: "Range Example"
  note: "Example for EIF4A1 transcript region matches (precise variants)"
  description: |
    As in the standard SNV query, this example shows a Beacon query against
    mutations in the `EIF4A1` gene in the DIPG childhood brain tumor dataset.
    However, this range + wildcard query will return any variant with
    alternate bases (indicated through "N").
    Since parameters will be interpreted using an "AND" paradigm, either <i>Alternate
    Bases</i> OR <i>Variant Type</i> should be specified.
    The exact variants which were being found can be retrieved through the variant
    handover [H—>O] link.
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    referenceName:
      defaultValue: "17" # "refseq:NC_000017.11"
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    aminoacidChange:
      isHidden: true
    start:
      defaultValue: 7572826
    end:
      defaultValue: 7579005
    variantType:
      defaultValue: "SO:0001059"
    alternateBases:
      defaultValue: ""
    referenceBases:
      defaultValue: ""
    limit:
      isHidden: true
    skip:
      isHidden: true
  img: https://docs.genomebeacons.org/img/BeaconRangeQuery-graphics.png

- label: "Gene Match"
  note: |
    Where supported beacons can discover variants overlap with the region of a known gene.
  description: |
    Beacons in v2 can support the discovery of variants with overlap with the
    genomic location of a gene, indicated by its symbol (e.g. `BRAF`). Additional
    parameters can _optionally_ be used to make matches more specific:
    - `variantMinLength` and `variantMaxLength` to limit matched CNV sizes
    - `genomicAlleleShortForm` (e.g. `V600E` with `BRAF`)
    - `variantType` and `alternateBases` to specify variants
    Here we also show the fields for some commonly used metadata elements.
  parameters:
    datasetIds:
      defaultValue: ["cellz"]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: false
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantMinLength:
      isHidden: false
    variantMaxLength:
      isHidden: false
    variantType:
      isHidden: false
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: true
    skip:
      isHidden: true
    limit:
      isHidden: true

- label: "Aminoacid Example"
  note: "Where supported beacons can discover variants by their aminoacid change."
  description: |
    Beacons in v2 can support the discovery of variants by their amino acid change
    in the single AA alteration form (e.g. "V600E"). For more specificity this
    parameter can be combined with the gene symbol (e.g. "BRAF").
  parameters:
    datasetIds:
      defaultValue: ["cellz"]
    aminoacidChange:
      isHidden: false
      defaultValue: V600E
    geneId:
      isHidden: false
      defaultValue:
        data:
          symbol: BRAF
        label: BRAF
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    variantType:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    skip:
      isHidden: true
    limit:
      isHidden: true
