---
note: ""
label: ""
description: ""
parameters:
  datasetIds:
    defaultValue: ["examplez"]
    options:
      - value: progenetix
        label: Progenetix
      - value: cellz
        label: Cancer Cell Lines Collection
      - value: examplez
        label: Test Database - examplez
  cohorts:
    defaultValue: [""]
  assemblyId:
    defaultValue: "GRCh38"
    isHidden: true
  referenceName:
    placeholder: "refseq:NC_000009.12"
  start:
    placeholder: "19000001-21975098"
  end:
    placeholder: "21967753-24000000"
  variantType:
    placeholder: "EFO:0030067"
  alternateBases:
    placeholder: "A"
  referenceBases:
    placeholder: "N"
  freeFilters:
    placeholder: ""
  accessid:
    isHidden: true
