---
- label: "CNV Example"
  note: "Example for focal CDKN2A deletion matches."
  description: |
    This example shows the query for CNV deletion variants overlapping the
    CDKN2A gene's coding region with at least a single base, but limited
    to "focal" hits (here i.e. <= ~2Mbp in size). The query is against the
    examplez collection and can be modified e.g. through changing the position
    parameters or data source.
  img: /img/BeaconBracketQuery-limited-match-graphics.png
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["examplez"]
    referenceName:
      isHidden: false
      defaultValue: "refseq:NC_000009.12"
    start:
      label: Start Bracket
      isHidden: false
      defaultValue: "21000001-21975098"
    end:
      label: End Bracket
      isHidden: false
      defaultValue: "21967753-23000000"
    variantType:
      isHidden: false
      defaultValue: "EFO:0030067"
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    allTermsFilters:
      isHidden: false
      defaultValue: [NCIT:C3058]

- label: "SNV Example"
  note: "Example for specific EIF4A1 mutation"
  description: |
    This example shows a core Beacon query, against a specific
    mutation in the EIF4A1 gene, in the DIPG childhood brain tumor dataset.
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["examplez", "progenetix"]
    referenceName:
      isHidden: false
      defaultValue: "refseq:NC_000017.11"
    start:
      isHidden: false
      defaultValue: 7577121
    variantType:
      isHidden: false
      defaultValue: "SO:0001059"
    alternateBases:
      isHidden: false
      defaultValue: "A"
    referenceBases:
      isHidden: false
      defaultValue: "G"

- label: "Range Example"
  note: "Example for EIF4A1 transcript region matches (precise variants)"
  description: |
    As in the standard SNV query, this example shows a Beacon query against
    mutations in the `EIF4A1` gene in the DIPG childhood brain tumor dataset.
    However, this range + wildcard query will return any variant with
    alternate bases (indicated through "N").
    Since parameters will be interpreted using an "AND" paradigm, either <i>Alternate
    Bases</i> OR <i>Variant Type</i> should be specified.
    The exact variants which were being found can be retrieved through the variant
    handover [H—>O] link.
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["cellz"]
    referenceName:
      isHidden: false
      defaultValue: "refseq:NC_000017.11"
    start:
      label: Range Start
      isHidden: false
      defaultValue: 7572826
    end:
      label: Range End
      isHidden: false
      defaultValue: 7579005
    variantType:
      isHidden: false
      defaultValue: "SO:0001059"
    alternateBases:
      isHidden: false
      defaultValue: ""
    referenceBases:
      isHidden: false
      defaultValue: ""
  img: /img/BeaconRangeQuery-graphics.png

- label: "Gene Match"
  note: |
    Where supported beacons can discover variants overlap with the region of a known gene.
  description: |
    Beacons in v2 can support the discovery of variants with overlap with the
    genomic location of a gene, indicated by its symbol (e.g. `CDK2`). Additional
    parameters can _optionally_ be used to make matches more specific:
    - `variantMinLength` and `variantMaxLength` to limit matched CNV sizes
    - `genomicAlleleShortForm` (e.g. `V600E` with `BRAF`)
    - `variantType` and `alternateBases` to specify variants
  img: /img/BeaconGeneQuery-graphics.png
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["cellz"]
    geneId:
      isHidden: false
      defaultValue: CDK2
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantMinLength:
      isHidden: false
      defaultValue: 10000
    variantMaxLength:
      isHidden: false
      defaultValue: 5000000
    variantType:
      isHidden: false
      defaultValue: "EFO:0030070"
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: true

- label: "Aminoacid Example"
  note: "Where supported beacons can discover variants by their aminoacid change."
  description: |
    Beacons in v2 can support the discovery of variants by their amino acid change
    in the single AA alteration form (e.g. "V600E"). For more specificity this
    parameter can be combined with the gene symbol (e.g. "BRAF").
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["cellz"]
    aminoacidChange:
      isHidden: false
      defaultValue: K132N
    geneId:
      isHidden: false
      defaultValue:
        data:
          symbol: TP53
        label: "TP53 (17:7668421-7687490)"
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantType:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true

- label: "Identifier - HeLa"
  note: "Samples can be identified through identifiers."
  description: |
    This example retrieves _HeLa_ instances - including cell lines derived from
    _HeLa_ - by _HeLa's_ _cellosaurus_ identifier `cellosaurus:CVCL_0030`.
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["cellz"]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantType:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    allTermsFilters:
      isHidden: true
    freeFilters:
      isHidden: false
      defaultValue: cellosaurus:CVCL_0030

- label: "Cytoband Example"
  note: "This is an experimental example for cytoband support."
  description: |
    This example shows a query for CNV gain variants in the cytoband 8q24.1, 
    the location of the MYC proto-oncogene, limited to ductal breast carcinomas.
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["examplez"]
    cytoBands:
      isHidden: false
      defaultValue: 8q24.1
    variantType:
      isHidden: false
      defaultValue: "EFO:0030070"
    allTermsFilters:
      isHidden: false
      defaultValue: [NCIT:C4017]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true

- label: "Variant Short Form Example"
  note: "This is an experimental example for short form vbariant(s) support."
  description: |
    This example shows a short form version of the CDKN2A deletion example.
  parameters:
    datasetIds:
      isHidden: false
      defaultValue: ["examplez"]
    cytoBands:
      isHidden: true
    variantQueryDigests:
      isHidden: false
      defaultValue: "9:21000001-21975098--21967753-24000000:DEL"
    variantType:
      isHidden: true
    allTermsFilters:
      isHidden: false
      defaultValue: [NCIT:C3058]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
