---
- label: "Bracket Query"
  note: "Query usein 2 `start` and 2 `end` values to find (structural) variants with some fuzziness for their start and end."
  description: |
    TBD
  img: https://docs.genomebeacons.org/img/BeaconBracketQuery-limited-match-graphics.png
  parameters:
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      placeholder: "refseq:NC_000009.12"
    start:
      placeholder: "21000001-21975098"
    end:
      placeholder: "21967753-23000000"
    variantType:
      placeholder: "EFO:0030067 (DEL)"
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    bioontology:
      isHidden: true
    clinicalClasses:
      isHidden: true
    materialtype:
      isHidden: true
    sex:
      isHidden: true
    freeFilters:
      placeholder: [NCIT:C3058]
    referenceid:
      isHidden: true
    cohorts:
      isHidden: true
    includeDescendantTerms:
      isHidden: true
    geoCity:
      isHidden: true
    geodistanceKm:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true
- label: "Range Query"
  note: "Query for variants with overlap to a genomic range"
  description: |
    TBD
  parameters:
    datasetIds:
      placeholder: ["examplez"]
    referenceName:
      isHidden: false
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    aminoacidChange:
      isHidden: true
    start:
      isHidden: false
    end:
      isHidden: false
    variantType:
      isHidden: false
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: false
    clinicalClasses:
      isHidden: true
    bioontology:
      isHidden: true
    sex:
      isHidden: true
    accessid:
      isHidden: true
    filterLogic:
      isHidden: true
    includeDescendantTerms:
      isHidden: true
    geoCity:
      isHidden: true
    geodistanceKm:
      isHidden: true
    freeFilters:
      isHidden: false
    materialtype:
      isHidden: true
    referenceid:
      isHidden: true
    cohorts:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true
  img: https://docs.genomebeacons.org/img/BeaconRangeQuery-graphics.png
- label: "Allele Request"
  note: 'This represents the inputs for a "classic" Beacon SNV query'
  description: |
    'This represents the inputs for a "classic" Beacon SNV query'
  parameters:
    datasetIds:
      placeholder: ["examplez"]
    referenceName:
      isHidden: false
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: true
    aminoacidChange:
      isHidden: true
    start:
      isHidden: false
    end:
      isHidden: true
    variantType:
      isHidden: false
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: false
    clinicalClasses:
      isHidden: true
    bioontology:
      isHidden: true
    sex:
      isHidden: true
    accessid:
      isHidden: true
    filterLogic:
      isHidden: true
    includeDescendantTerms:
      isHidden: true
    geoCity:
      isHidden: true
    geodistanceKm:
      isHidden: true
    freeFilters:
      isHidden: false
    materialtype:
      isHidden: true
    referenceid:
      isHidden: true
    cohorts:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true
  img: false
- label: "Aminoacid Variant"
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    aminoacidChange:
      isHidden: false
    geneId:
      isHidden: false
    genomicAlleleShortForm:
      isHidden: true
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    variantType:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    bioontology:
      isHidden: true
    clinicalClasses:
      isHidden: true
    accessid:
      isHidden: true
    filterLogic:
      isHidden: true
    includeDescendantTerms:
      isHidden: true
    geoCity:
      isHidden: true
    geodistanceKm:
      isHidden: true
    freeFilters:
      isHidden: false
    sex:
      isHidden: true
    materialtype:
      isHidden: true
    referenceid:
      isHidden: true
    cohorts:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true


- label: "Genomic HGVS"
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    aminoacidChange:
      isHidden: true
    geneId:
      isHidden: true
    genomicAlleleShortForm:
      isHidden: false
    referenceName:
      isHidden: true
    start:
      isHidden: true
    end:
      isHidden: true
    variantMinLength:
      isHidden: true
    variantMaxLength:
      isHidden: true
    variantType:
      isHidden: true
    alternateBases:
      isHidden: true
    referenceBases:
      isHidden: true
    bioontology:
      isHidden: true
    clinicalClasses:
      isHidden: true
    accessid:
      isHidden: true
    filterLogic:
      isHidden: true
    includeDescendantTerms:
      isHidden: true
    geoCity:
      isHidden: true
    geodistanceKm:
      isHidden: true
    freeFilters:
      isHidden: false
    sex:
      isHidden: true
    materialtype:
      isHidden: true
    referenceid:
      isHidden: true
    cohorts:
      isHidden: true
    limit:
      isHidden: true
    skip:
      isHidden: true


- label: "All Fields"
  parameters:
    datasetIds:
      defaultValue: ["examplez"]
    aminoacidChange:
      isHidden: false
    geneId:
      isHidden: false
    genomicAlleleShortForm:
      isHidden: false
    referenceName:
      isHidden: false
    start:
      isHidden: false
    end:
      isHidden: false
    variantMinLength:
      isHidden: false
    variantMaxLength:
      isHidden: false
    variantType:
      isHidden: false
    alternateBases:
      isHidden: false
    referenceBases:
      isHidden: false
    bioontology:
      isHidden: false
    clinicalClasses:
      isHidden: false
    accessid:
      isHidden: false
    filterLogic:
      isHidden: false
    includeDescendantTerms:
      isHidden: false
    geoCity:
      isHidden: false
    geodistanceKm:
      isHidden: false
    freeFilters:
      isHidden: false
    sex:
      isHidden: false
    materialtype:
      isHidden: false
    referenceid:
      isHidden: false
    cohorts:
      isHidden: false
    limit:
      isHidden: true
    skip:
      isHidden: true


